[build]
  base = "/"
  publish = "/"
  command = "echo 'Static site, no build needed'"

[[redirects]]
  from = "/flipbook/*"
  to = "/flipbook/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
